export const metadataValues = {
  0: {
    type: 'Level',
    displayType: 'number',
    maxValue: 3,
    values: {
      1: 1,
      2: 2,
      3: 3,
    },
  },
  1: {
    type: 'Background/Board',
    values: {
      0: 'Flame Surfboard Sea Island',
      1: 'Green Surfboard Sea Island',
      2: 'Green Engine Surfboard Sea Island',
      3: 'Green Surfboard Beach Sand',
      4: 'Black Hoverboard Beach Sand',
      5: 'Brown Engine Hoverboard Beach Sand',
      6: 'Black/Gray Hoverboard Sky',
      7: 'Black Hoverboard Sky',
      8: 'Gray Hoverboard Sky',
      9: 'Brown Engine Hoverboard Sky',
      10: 'Yellow Engine Hoverboard Sky',
      11: 'Black/Gray Hoverboard Heaven',
      12: 'Black Hoverboard Heaven',
      13: 'Gray Hoverboard Heaven',
      14: 'Yellow Engine Hoverboard Heaven',
      15: 'Blue Surfboard Oasis',
      16: 'Black/Gray Hoverboard Oasis',
      17: 'Gray Hoverboard Oasis',
      18: 'Yellow Engine Hoverboard Oasis',
      19: 'Blue Snowboard Oasis',
      20: 'Green Snowboard Oasis',
      21: 'Red Rocket Skateboard Sidewalk',
      22: 'Brown Skateboard Sidewalk',
      23: 'Gray Skateboard Sidewalk',
      24: 'Green Skateboard Sidewalk',
      25: 'Pink Skateboard Sidewalk',
      26: 'Purple Snakeboard Sidewalk',
      27: 'Purple Rocket Skateboard Street',
      28: 'Brown Skateboard Street',
      29: 'Gray Skateboard Street',
      30: 'Green Skateboard Street',
      31: 'Pink Skateboard Street',
      32: 'Purple Snakeboard Street',
      33: 'Flame Surfboard Desert',
      34: 'Black Hoverboard Desert',
      35: 'Brown Engine Hoverboard Desert',
      36: 'Black Snowboard Desert',
      37: 'Purple Chain Drive Snowboard Desert',
      38: 'Yellow Engine Hoverboard Igloo',
      39: 'Black Snowboard Igloo',
      40: 'Blue Snowboard Igloo',
      41: 'Brown Snowboard Igloo',
      42: 'Green Snowboard Igloo',
      43: 'Purple Chain Drive Snowboard Igloo',
      44: 'Brown Engine Hoverboard Slope',
      45: 'Black Snowboard Slope',
      46: 'Blue Snowboard Slope',
      47: 'Brown Snowboard Slope',
      48: 'Green Snowboard Slope',
      49: 'Purple Chain Drive Snowboard Slope',
      50: 'Green Rocket Skateboard Skate Park',
      51: 'Brown Skateboard Skate Park',
      52: 'Gray Skateboard Skate Park',
      53: 'Green Skateboard Skate Park',
      54: 'Pink Skateboard Skate Park',
      55: 'Purple Snakeboard Skate Park',
      56: 'Purple Rocket Skateboard Route 95',
      57: 'Brown Skateboard Route 95',
      58: 'Gray Skateboard Route 95',
      59: 'Green Skateboard Route 95',
      60: 'Pink Skateboard Route 95',
      61: 'Purple Snakeboard Route 95',
      62: 'Flame Surfboard Beach',
      63: 'Green Surfboard Beach',
      64: 'Green Engine Surfboard Beach',
      65: 'Black/Gray Hoverboard Beach',
      66: 'Blue Surfboard Cliffs',
      67: 'Yellow Engine Surfboard Cliffs',
      68: 'Green Engine Surfboard Cliffs',
      69: 'Gray Hoverboard Cliffs',
      70: 'Blue Surfboard Wave',
      71: 'Yellow Engine Surfboard Wave',
    },
  },
  2: {
    type: 'Shell',
    values: {
      0: {
        1: 'LVL1 Regular',
        2: 'LVL2 Regular',
        3: 'LVL3 Regular'
      },
      1: {
        1: 'LVL1 Robot',
        2: 'LVL2 Robot',
        3: 'LVL3 Robot',
      },
      2: {
        1: 'LVL1 Pink',
        2: 'LVL2 Pink',
        3: 'LVL3 Pink',
      },
      3: {
        1: 'LVL1 Rocky',
        2: 'LVL2 Rocky',
        3: 'LVL3 Rocky',
      },
      4: {
        1: 'LVL1 Dark',
        2: 'LVL2 Dark',
        3: 'LVL3 Dark',
      },
      5: {
        1: 'LVL1 Shiny',
        2: 'LVL2 Shiny',
        3: 'LVL3 Shiny',
      },
      6: {
        1: 'LVL1 Armed',
        2: 'LVL2 Armed',
        3: 'LVL3 Armed',
      },
      7: {
        1: 'LVL1 Matrix',
        2: 'LVL2 Matrix',
        3: 'LVL3 Matrix',
      },
      8: {
        1: 'LVL1 Military',
        2: 'LVL2 Military',
        3: 'LVL3 Military',
      },
      9: {
        1: 'LVL1 Psychedelic',
        2: 'LVL2 Psychedelic',
        3: 'LVL3 Psychedelic',
      },
      10: {
        1: 'LVL1 Wood',
        2: 'LVL2 Wood',
        3: 'LVL3 Wood',
      },
      11: {
        1: 'LVL1 Zebra',
        2: 'LVL2 Zebra',
        3: 'LVL3 Zebra',
      },
    },
  },
  3: {
    type: 'Eyes',
    values: {
      0: 'Normal',
      1: 'Scared',
      2: 'Angry',
      3: 'Blink',
      4: 'Sceptical',
      5: 'Striped Glasses',
      6: 'Glasses',
      7: 'Goggles',
      8: 'Crazy',
      9: 'Heart Glasses',
      10: 'Normal Blue',
      11: 'Cyborg',
      12: 'Sunglasses',
      13: 'Terminator',
      14: 'Closed',
      15: 'Crying',
      16: 'Surprised',
      17: 'Dollar',
      18: 'Blood',
      19: 'Laser',
      20: 'Mask',
      21: 'Scared Yellow',
      22: 'Angry Red',
      23: 'Blink Green',
      24: 'Sceptical Red',
      25: 'Crazy Green',
      26: 'Surprised Blue',
    },
  },
  4: {
    type: 'Mouth',
    values: {
      0: 'Normal',
      1: 'Yawn',
      2: 'Tongue',
      3: 'Kiss',
      4: 'Teeth',
      5: 'Gold Tooth',
      6: 'Open',
      7: 'Sad Open',
      8: 'Crying',
      9: 'Cigarette',
      10: 'Cigar',
      11: 'Sad Closed',
      12: 'Teeth Clench',
      13: 'Twist',
      14: 'Goofy',
      15: 'Angry',
      16: 'Drooling',
      17: 'Vampire',
      18: 'Blood',
    },
  },
  5: {
    type: 'Skin',
    values: {
      0: 'Normal',
      1: 'Spotted Green',
      2: 'Spotted Red',
      3: 'Tattoos',
      4: 'Scars',
      5: 'Cyborg Blue',
      6: 'Cyborg Red',
      7: 'Scales',
      8: 'Bandages',
      9: 'Patches',
      10: 'Azure',
      11: 'Blue',
      12: 'Pink',
      13: 'Orange',
      14: 'Yellow',
      15: 'Red',
      16: 'Purple',
      17: 'Spotted Azure',
      18: 'Spotted Yellow',
      19: 'Spotted Purple',
      20: 'Rainbow',
      21: 'Check Azure',
      22: 'Check Pink',
      23: 'Skull Blue',
      24: 'Skull Red',
      25: 'Skull Purple',
      26: 'Leopard Pink',
      27: 'Leopard Orange',
      28: 'Leopard Yellow',
    },
  },
  6: {
    type: 'Head',
    values: {
      0: 'None',
      1: 'Baseball Cap',
      2: 'Reverse Baseball Cap',
      3: 'Propeller Cap',
      4: 'Silk Black',
      5: 'Cowboy Hat Brown',
      6: 'Cowboy Hat White',
      7: 'Silk Red',
      8: 'Crown',
      9: 'Bandana Red',
      10: 'Bandana Black',
      11: 'Mohawk Pink',
      12: 'Mohawk Green',
      13: 'Long Blonde',
      14: 'Short Brown',
      15: 'Long Black',
      16: 'Medium Red',
      17: 'Medium Brown',
      18: 'Short Blonde',
      19: 'Curl Black',
      20: 'Curl Blonde',
      21: 'Pirate',
      22: 'Knight',
      23: 'Captain',
      24: 'Mohawk Rainbow',
      25: 'Flower',
      26: 'Halo',
      27: 'Turban',
    },
  },
  7: {
    type: 'Jewellery',
    values: {
      0: 'None',
      1: 'Necklace Silver',
      2: 'Diamond Necklace',
      3: 'Piercing Silver',
      4: 'Ring Gold',
      5: 'Armlet Gold',
      6: 'Necklace Gold',
      7: 'Studded Armlet',
      8: 'Necklace Ethereum',
      9: 'Necklace Bitcoin',
      10: 'Necklace Dollar',
      11: 'Necklace Bell',
      12: 'Pearl Necklace',
      13: 'Necklace Hawaii',
      14: 'Diamond Hands',
      15: 'Bowtie Black',
      16: 'Bowtie Pink',
    },
  },
  8: {
    type: 'Shoes',
    values: {
      0: 'None',
      1: 'Sneakers Green',
      2: 'Slippers Red',
      3: 'Slippers Blue',
      4: 'Gumboots Black',
      5: 'Gumboots Yellow',
      6: 'Runners Black',
      7: 'Boots Brown',
      8: 'Boots Purple',
      9: 'Sneakers Red',
      10: 'Clown',
      11: 'Cowboy',
      12: 'High Sneakers Black',
      13: 'High Sneakers Red',
      14: 'High Sneakers Blue',
      15: 'Sneakers Pink/Green',
      16: 'Sneakers Blue',
      17: 'Sneakers Brown',
      18: 'Runners Red',
      19: 'Runners Purple',
      20: 'Runners Blue',
    },
  },
  aura: {
    type: 'Aura',
    values: {
      1: 'LVL1 Silver',
      2: 'LVL2 Gold',
      3: 'LVL3 Red',
    },
  },
};
